Initial commit
canvasland-nft/marketplace pull request #36
Opened 2022-05-20 17:28 UTC by pracheebapate

2022-05-23 11:14 UTC, kyawthetkt approved these changes

2022-05-24 06:15 UTC, shakil-adv requested changes

2022-05-24 06:15 UTC, shakil-adv commented on src/pages/collections/single/CreateEdit.js
> +        navigate('/my-collections');
Please navigate to `user/userAddress/collections`

2022-05-24 06:44 UTC, jibrail-idris commented on src/pages/collections/single/CreateEdit.js
> +                if(collection.get('contractAddress') === undefined
Javascript has two possible not defined values
`undefined` or `null`.

2022-05-24 07:32 UTC, pracheebapate commented on src/pages/collections/single/CreateEdit.js
> +        navigate('/my-collections');
Done.

2022-05-24 07:32 UTC, pracheebapate commented on src/pages/collections/single/CreateEdit.js
> +                if(collection.get('contractAddress') === undefined
Done changed to `if(!collection.get('contractAddress'))`

2022-05-24 07:34 UTC, shakil-adv approved these changes

2022-05-24 07:36 UTC, merged